apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hukh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-hukh@sha256:5bc6b13f97f36eb2ec5dc3836eafd012d5651041a972f763dd0d8966d3f0b1e3
        name: my-nodejs
        resources: {}
status: {}
